[package]
name = "mandelbrot_proc_macros"
version = "0.1.0"
edition = "2024"

[lib]
name = "mandelbrot_proc_macros"
proc-macro = true

[dependencies]
syn = { version = "2.0.100", features = ["full", "visit-mut"] }
quote = "1.0.40"